### ISSUE TITLE
Typo in filename

### ISSUE THREAD

**Issue by rweymann** [PIT-Solutions-Private-Limited/deepltranslate#2]
After installing typo3 throws the following Error

Class 'PITS\Deepltranslate\Domain\Repository\DeeplSettingsRepository' not found

in /var/www/html/public/typo3/sysext/core/Classes/Utility/GeneralUtility.php line 3662
        ) {
            return array_shift(self::$nonSingletonInstances[$finalClassName]);
        }
        // Create new instance and call constructor with parameters
        $instance = new $finalClassName(...$constructorArguments);
        // Register new singleton instance
        if ($instance instanceof SingletonInterface) {
            self::$singletonInstances[$finalClassName] = $instance;
        }
at TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance('PITS\\Deepltranslate\\Domain\\Repository\\DeeplSettingsRepository')
in /var/www/html/public/typo3conf/ext/deepltranslate/Classes/Service/DeeplService.php line 78

Reason is a typo in public/typo3conf/ext/deepltranslate/Classes/Domain/Repository/DeeplSettingsRepostory.php
that should be 
public/typo3conf/ext/deepltranslate/Classes/Domain/Repository/DeeplSettingsRepository.php

**Comment by rickymathew** [comment]
Thanks @rweymann  for notifying the issue. I guess you tried to install it via composer right? Actually i didn't checked it thoroughly for composer installation.Sorry for that.I wonder , why dont the inhouse class autoloader (installation via extension manager) for TYPO3 didn't throw the class resolution issue.Anyway fixed the typo.Can you check it again?

**Comment by rweymann** [comment]
There's nothing changed until now. Maybe packagist needs some time to update. What do you think?

**Comment by rickymathew** [comment]
you need to checkout dev-master.Otherwise i have to tag it with version 1.0.5. Everything got updated in packagist as i alredy enabled webhook.

**Comment by rweymann** [comment]
With dev-master checkout the issue is fixed. Thank you!
