### ISSUE TITLE
Translate button disabled

### ISSUE THREAD

**Issue by tlogfred** [PIT-Solutions-Private-Limited/deepltranslate#3]
After installing the extension the translate button everywhere is disabled. Is there anything more to do, which is not described in the manual? TYPO3 8.7.24 and deeptranslate 1.0.2

**Comment by rickymathew** [comment]
Hi @tlogfred ,actually 1.0.2 don't support 8 LTS.We had a mistake that we didn't remove the support in that version.deepltranslate 1.0.2 onwards only support 9 LTS.In extension management section we tried to remove the version 1.0.2 to avoid confusion ,but it provides no option to remove a specific version.So we just hinted it in requirements section(https://github.com/PIT-Solutions-Private-Limited/deepltranslate#requirements).Sorry for the confusion.

**Comment by tlogfred** [comment]
Ok, thank you.
