### ISSUE TITLE
Missing items in extension configuration

### ISSUE THREAD

**Issue by markgraf** [PIT-Solutions-Private-Limited/deepltranslate#9]
Typo3-Version: 9.5.14
deepltranslate-Version: 1.0.4

Extension configuration is missing a field to paste deepl API-Key:

![deepl_settings](https://user-images.githubusercontent.com/1706270/75907822-4ca92b00-5e49-11ea-9016-43ee3ec0a97f.png)

Please advise.

**Comment by chinnupits** [comment]
@markgraf 
The extension related settings need to set in ADMIN TOOL->Settings->Extension Configuration session.

**Comment by markgraf** [comment]
Thanks! That works :-)
